# Generated by Django 3.2.12 on 2022-03-29 04:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import watch.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('firstname', models.CharField(max_length=32, verbose_name='firstname')),
                ('lastname', models.CharField(max_length=32, verbose_name='lastname')),
                ('phone', models.CharField(max_length=11, validators=[watch.validators.check_phone], verbose_name='phone')),
                ('email', models.EmailField(max_length=64, verbose_name='email')),
                ('birthday', models.DateField(default=datetime.datetime.now, verbose_name='birthday')),
                ('gender', models.BooleanField(verbose_name='gender')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='username')),
                ('watch_code', models.IntegerField(verbose_name='watch_code')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_1', models.CharField(max_length=32, null=True, verbose_name='contact_1')),
                ('phone_1', models.CharField(max_length=11, null=True, validators=[watch.validators.check_phone], verbose_name='phone_1')),
                ('contact_2', models.CharField(max_length=32, null=True, verbose_name='contact_2')),
                ('phone_2', models.CharField(max_length=11, null=True, validators=[watch.validators.check_phone], verbose_name='phone_2')),
                ('contact_3', models.CharField(max_length=32, null=True, verbose_name='contact_3')),
                ('phone_3', models.CharField(max_length=11, null=True, validators=[watch.validators.check_phone], verbose_name='phone_3')),
                ('contact_4', models.CharField(max_length=32, null=True, verbose_name='contact_4')),
                ('phone_4', models.CharField(max_length=11, null=True, validators=[watch.validators.check_phone], verbose_name='phone_4')),
                ('contact_5', models.CharField(max_length=32, null=True, verbose_name='contact_4')),
                ('phone_5', models.CharField(max_length=11, null=True, validators=[watch.validators.check_phone], verbose_name='phone_4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
