# Generated by Django 3.2.12 on 2022-04-14 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0002_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceleratorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.SmallIntegerField(verbose_name='event')),
                ('x', models.FloatField(verbose_name='x')),
                ('y', models.FloatField(verbose_name='y')),
                ('z', models.FloatField(verbose_name='z')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
