# Generated by Django 3.2.12 on 2022-04-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0003_acceleratordata'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='code')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='watch_code',
            field=models.CharField(max_length=16, unique=True, verbose_name='watch_code'),
        ),
    ]
