# Generated by Django 3.2.12 on 2022-04-27 15:05

from django.db import migrations, models
import watch.validators


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0004_auto_20220418_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceleratordata',
            name='situation',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_5',
            field=models.CharField(max_length=32, null=True, verbose_name='contact_5'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_5',
            field=models.CharField(max_length=11, null=True, validators=[watch.validators.check_phone], verbose_name='phone_5'),
        ),
    ]
